### PR TITLE
Settings Helper Class - Bug fix

### PR DESCRIPTION
**Pull request by nefeline**
https://central.tri.be/issues/81946

### CODE REVIEW

**Review by barryhughes — APPROVED** [review]

**Comment by barryhughes** [comment]
:cactus:

**Comment by cliffordp** [comment]
Nice that we could do all these at once :)

1. This is a good opportunity to correct 404 errors. I already added the redirect so these are no longer 404s, but we should have the accurate URLs in each extension.
A. Change https://theeventscalendar.com/extensions/the-events-calendar-main-blog-loop/ to https://theeventscalendar.com/extensions/advanced-options-for-adding-events-to-the-main-blog-loop/
B. Change https://theeventscalendar.com/extensions/the-events-calendar-relabeler/ to https://theeventscalendar.com/extensions/extensions/change-labels-events-venues-organizers/
C. Change https://theeventscalendar.com/extensions/extensions/selectively-show-html-before-after-content/ to https://theeventscalendar.com/extensions/extensions/display-custom-html-specific-calendar-views/
2. I see you changed existing `set_version()` versions, which is great, but we need to _add_ the `set_version()` whenever changing from v1.0.0 to the next version. Basically, `set_version()` always exists except for v1.0.0... that is until we rework the extensions framework.

**Review by cliffordp — CHANGES_REQUESTED** [review]
See https://github.com/moderntribe/products-extensions/pull/54#issuecomment-355349126

**Review by cliffordp — APPROVED** [review]
thanks for making the requested changes

**Pull request merged**
