### PR TITLE
EA Facebook Dev Origin

### PR DESCRIPTION
**Pull request by sc0ttkclark**

### CODE REVIEW

**Comment by barryhughes** [comment]
Hey quick note, Scott — we're trying to transition away from using this repo. 

Your call if you want to keep things here in the interests of expediency, but where possible we're trying to house each extension in its own repository [(over here)](https://github.com/mt-support/). That way, there is one repo per plugin and things are a bit saner (vs having one plugin per directory in a single huge repo).

**Comment by sc0ttkclark** [comment]
Fine by me, can a repo be created for me?

**Comment by barryhughes** [comment]
Definitely: https://github.com/mt-support/tribe-ext-ea-facebook/

**Comment by sc0ttkclark** [comment]
Moved the code here: https://github.com/mt-support/tribe-ext-ea-facebook/pull/1

**Pull request closed without merging**
